### ISSUE TITLE
add libcombine  / zipper 

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/sme_deps_common#21]
I saw, that in the last commit  you removed the  zlib library. In order to be able to open OMEX archives with SME, i was hoping to add: 

* <https://github.com/fbergmann/zipper>  and
*  <https://github.com/sbmlteam/libCombine> 

to the common deps. It would however also require zlib. So i was wondering why it was removed it in the first place.

**Comment by lkeegan** [comment]
zlib is still there, just it is now built as part of  https://github.com/spatial-model-editor/sme_deps_qt so that qt can link to it as well, as previously qt would build it's own version of zlib and then we ended up with two different static zlib libraries (https://github.com/spatial-model-editor/sme_deps_common/issues/18)

**Comment by fbergmann** [comment]
I was just wondering where to add combine / zipper. Since it would be useful to have the capability to read combine archives not just from the gui, but from the bindings as well. Basically the plan would be to make it part of the load step to see whether the file loaded is an archive, and if so go through the libcombine.

**Comment by lkeegan** [comment]
Here would be the place to add them (as well as to https://github.com/spatial-model-editor/sme_manylinux2014_x86_64 for the python wheels)

I have a WIP here: https://github.com/spatial-model-editor/sme_deps_common/pull/22

(ran into some issues with building zipper on msys/mingw, patches here (also a WIP!): https://github.com/lkeegan/zipper/commit/fff200af92c9b203f6b171da70cf3cd1b2d05b92)

**Comment by lkeegan** [comment]
resolved by #22
